# 파일에서 데이터를 불러오는 방식

In [2]:
%%writefile x.csv
1,2,3
4,5,6
7,8,9

Writing x.csv


In [3]:
# 파일생성 매직워드

In [4]:
import numpy as np

In [8]:
a = np.fromfile('x.csv', sep=',')
# 파일로부터 numpy생성하는 함수
# but 자주 안쓰임

In [9]:
a
# 개행 문자를 인식 못해서 1,2,3만 가져옴

array([1., 2., 3.])

In [11]:
a = np.loadtxt('x.csv', delimiter=',')
# 파일을 불러오면서 동시에 numpy format으로 바꿔줌
# 옵션이 별로 없어서 아쉽...,
# 그래도 더 많이 쓰인다. (에러가 날 때 에러를 출력해주므로...)

In [12]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [15]:
b = np.genfromtxt('x.csv')
# 엉터리로 불렀는데 에러가 안 남 (안 좋은 방식)

In [16]:
b

array([nan, nan, nan])

In [17]:
b = np.genfromtxt('x.csv', delimiter=',')

In [18]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

np.fromfile  
np.loadtxt  
np.genfromtxt  
파일에 있는 데이터를 numpy format으로 변환시킨다.