# c로 만든 python은 왜 c만큼 안 빠른 것일까?  
type이 없어서 해당 type에 attribute가 존재하는지 매 순간 확인하므로 속도가 느리다.  

python : 타입을 명확하게 작성 안해도 되므로 사람한테 편하다.  

c언어 : 한번에 assembly언어로 만들어서 최적화 시킨다.  
인터프리터는 한 줄 한 줄 체크함 == 사람입장에서는 더 편하다

python list : 동적이라서 알아서 크기를 관리해준다. & hetero가능 == 사용자에게 편함  
    
numpy : type check안해도 됨, 메모리 구조상 빠르다.

numpy가 느린 경우:
    
1. 데이터 사이즈가 작을 경우 느리다. == numpy객체로 변환시킬 때 cost가 소모됨
2. 니가 잘못함 ^~^

# np.shape, np.dtype만으로 다른 정보를 파생시킬 수 있음
# 2개만 숙지하고 있으면 될 듯

numpy는 무조건 homogeneous이다. == type check안해서 훨씬 빠르다.  
numpy객체 생성할 때 type을 맞춘다.
``` python
>>> b = np.array([(1.5,2,3), (4,5,6)])
>>> b
array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])
```   
더 큰 type으로 변환시킨다.

---

# print 에서 shape읽는 방법

``` python
>>> c = np.arange(24).reshape(2,3,4)         # 3d array
>>> print(c)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]
 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
```
# 괄호 하나 없애면 원소 2개
``` python
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
원소 2개
```

# 괄호 2개 없애면 원소 3개
``` python
[ 0  1  2  3]
[ 4  5  6  7]
[ 8  9 10 11]

```

# 괄호 3개 없애면 원소 4개
0  1  2  3

# [basic operation](https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations)은 shape를 맞춰야 한다.
# [universal function](https://docs.scipy.org/doc/numpy/user/quickstart.html#broadcasting-rules)은 shape를 안맞춰도 broadcasting해줘서 계산해준다.

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3])

In [9]:
b = np.array([[1,2],[3,2],[3,4]])

In [10]:
a[np.newaxis] @ b
# 2차원

array([[16, 18]])

In [11]:
a @ b 
# 1차원

array([16, 18])

원하는 결과(차원)에 따라서 np.newaxis를 넣는다.

indexing && slicing 쓰는 용도??  
빅데이터는 직접 만들기 보다는 원래 있던 데이터에서 내가 원하는 데이터를 추출핲 때 indexing, slicing을 사용한다.

# ravel : 1차원 만들어줘서 view를 
# flatten : copy

In [16]:
# universal function : 여러개의 값을 한번에 처리할 수 있다. == vectorize == 속도 매우 빠르고 메모리 효율적이다.
import math
math.sqrt([3,4])
# 여러개 계산하는 것 불가능

TypeError: must be real number, not list

In [15]:
np.sqrt([4,9])
# 여러개 계산 가능

array([2., 3.])

ix_ : 함수 cartesian product

# numpy는 선형대수 기법을 제공해줌
vectorize == 속도 매우 빠르고 메모리 효율적이다.