# np.newaxis사용하는 이유 : 연산을 하기 위해서는 형태 맞춰야 한다.

# [] 감싼다 == 차원을 하나 증가시켜준다는 의미

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
# (3,) : 아직 row vector인지 column인지 모른다.
# 이 객체는 행과 열이 없다.

In [3]:
a[np.newaxis]
# a[np.newaxis,:]
# x축제 추가하면 양끝에 []를 추가해준다. == 행을 추가해준다.
# 차원을 높여줌

array([[1, 2, 3]])

In [4]:
a[:,np.newaxis]
# 행은 그대로, 열을 추가시킴 == []로 감쌈
# 열마다 꺽쇠를 추가한다.
# 차원을 증가시켜준다.

array([[1],
       [2],
       [3]])

In [5]:
b = np.array([[1,2,3],[4,5,6]])

In [13]:
# x축 차원 증가시키고 싶을 때
b.reshape(1,-1,-1)
# 자동 완성은 하나만 가능하다

ValueError: can only specify one unknown dimension

In [14]:
# 차원 확장하고 싶은 곳에 1을 넣는다.
b.reshape(1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [7]:
b[np.newaxis]
# 밖에 []로 감싼다.
# 행의 차원을 증가시켜줌
# 

array([[[1, 2, 3],
        [4, 5, 6]]])

In [15]:
b.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [8]:
b[:,np.newaxis]
# b[:,np.newaxis,:]
# 바깥 []하나 빼고 각 원소들을 []로 감쌈
# 열의 차원을 증가시켜줌
# [1,2,3]와 [4,5,6] == 각 열의 차원을 증가시켜줌

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [16]:
b.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [9]:
b[:,:,np.newaxis]
# 바깥[]2개 빼고 각 원소들을 []로 감쌈
# [[1, 2, 3]] 에서 [[]] 빼고 각 원소를 []로 감쌈
# 높이의 차원을 증가시켜줌

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [17]:
# 보통 reshape사용할 것을 권장함 newaxis는 어려우니까...
# -1 : 알아서 자동완성해줌
# 2개 -1넣으면 자동으로 못한다.