In [2]:
import numpy as np

In [4]:
a = np.arange(25).reshape(5, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
a[0][2:4]
# python 방식

array([2, 3])

# numpy방식
내가 필요한 데이터를 뽑아내는 기법

In [7]:
a[0,2:4]
# numpy 방식

array([2, 3])

In [8]:
a[0,[2,3]]
# numpy 방식

array([2, 3])

In [9]:
a[[0,0],[2,3]]
# (0,2), (0,3) 을 가져옴

array([2, 3])

In [11]:
a[np.ix_([0],[2,3])] # np.ix_ cartesian product
# 값을 가지고 오는데 결과값이 약간 다르다.

array([[2, 3]])

In [12]:
a[[-2,-1]][:,-2:]

array([[18, 19],
       [23, 24]])

In [13]:
a[[-2,-1],[:,-2:]]
# 양쪽 []에 갯수가 안 맞아서 오류남
# 짝을 맞춰야 하므로... 행--열

SyntaxError: invalid syntax (<ipython-input-13-5610185acf44>, line 1)

In [14]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [17]:
a[[2,4]][:,::2]
# [[]] 면 fancy indexing
# 행부터 뽑아내는것이 핵심..!
# ::2 처음부터 끝까지 2 stride로 뽑아냄

array([[10, 12, 14],
       [20, 22, 24]])

In [18]:
a[[2,-1],[2,2]]

array([12, 22])

In [19]:
a[[True,False,True,False,True],2]
# [[행], 열]

array([ 2, 12, 22])

# Broadcasting (편리한 기능)
다른 수치해석 언어에도 broadcasting기능이 있음

네트워크의 broadcasting과 다름

In [35]:
a = np.array([1,2,3])

In [36]:
a

array([1, 2, 3])

In [37]:
a + 3
# broadcasting(크기 자동으로 맞춰주는 기법)
# 각 원소를 3 더한 것과 같다. element-wise addition
# R, matlab에 있음
# 자동으로 3이 array([3,3,3])이 됨

array([4, 5, 6])

In [38]:
3*a
# 자동으로 3이 array([3,3,3])이 됨
# element-wise product
# 각각의 원소를 곱하는 것이 default

array([3, 6, 9])

python에서는..?

In [22]:
[1, 2, 3] + 3
# 덧셈은 같은 type만 가능

TypeError: can only concatenate list (not "int") to list

In [23]:
[1, 2, 3] + [3]
# concatenate

[1, 2, 3, 3]

In [25]:
t = [1,2,3].extend([4]) # iterable을 넣어야 하므로

In [26]:
t

# mutable객체의 method의 return값을 조심하기
1. 자기 자신은 바꾸지만,  None을 반환함
2. 자기 자신은 안바꾸고, 값을 반환
3. 자기 자신은 바꾸고, 값을 반환

In [28]:
a = [1,2,3]

In [29]:
a.append(4) #1. 자기 자신은 바꾸지만,  None을 반환함

In [30]:
a

[1, 2, 3, 4]

In [31]:
a.index(3) # 2. 자기 자신은 안바꾸고, 값을 반환

2

In [32]:
a.pop() # 3. 자기 자신은 바꾸고, 값을 반환

4

In [33]:
a

[1, 2, 3]

# ufunc = universal function : vectorize를 지원해서 보통 함수보다 빠르다
== 한꺼번에 계산을 해준다.  
numpy format(자료구조)을 안써도 되는거고, 여러개 원소도 한꺼번에 계산함(vectorize)

한개만 넣어도 되고 여러개 넣어도 됨

universal : 보편적인 계산을 해준다고해서 universal : math에도 대부분 있음

In [39]:
np.sum(range(10))

45

In [41]:
np.sqrt([2,3,4])
# math

1.4142135623730951

In [42]:
import math

In [44]:
math.sqrt([2,3,4])
# 여러개를 못 씀

TypeError: must be real number, not list

# 수학 계산할 것이 있으면 numpy로 계산하자.

# scipy는 더 많은 기능을 가지고 있다. (numpy기반)

In [45]:
from scipy import special

In [46]:
special.factorial([3,4])

array([ 6., 24.])

소스코드 추출하는 방법

In [47]:
import inspect

In [51]:
# 함수이기 때문에 상속은 힘들고 copy & paste 혹은 decorator써서 기능 바꿈
# class만 상속 가능
print(inspect.getsource(special.factorial))

def factorial(n, exact=False):
    """
    The factorial of a number or array of numbers.

    The factorial of non-negative integer `n` is the product of all
    positive integers less than or equal to `n`::

        n! = n * (n - 1) * (n - 2) * ... * 1

    Parameters
    ----------
    n : int or array_like of ints
        Input values.  If ``n < 0``, the return value is 0.
    exact : bool, optional
        If True, calculate the answer exactly using long integer arithmetic.
        If False, result is approximated in floating point rapidly using the
        `gamma` function.
        Default is False.

    Returns
    -------
    nf : float or int or ndarray
        Factorial of `n`, as integer or float depending on `exact`.

    Notes
    -----
    For arrays with ``exact=True``, the factorial is computed only once, for
    the largest input, with each other result computed in the process.
    The output dtype is increased to ``int64`` or ``object`` if necessary.

    With ``exact

함수의 종류가 다양하므로 np.info, shift + tap으로 정보를 찾아봐야한다.

In [52]:
type(np.sum)

function

In [66]:
type(np.sqrt)
# broadcasting을 지원하는 함수
# vectorize할 수 있음(한개 넣어도 되고, 여러개 넣어도 됨)
# numpy format뿐만 아니라 다른 format도 받음 (tuple넣어도 됨 == duck typing)

numpy.ufunc

In [54]:
type(np.dot)
# function도 되고 mehotd로도 쓸 수 있음

builtin_function_or_method

In [55]:
# help랑 같은 기능
np.info(np.sqrt)

sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the non-negative square-root of an array, element-wise.

Parameters
----------
x : array_like
    The values whose square-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray
    An array of the same shape as `x`, containing the positive
    square-root of each element in `x`.

In [58]:
a = np.arange(10)
np.where(a>4,1,0) # select from where SQL, where이 sql이랑 유사
# 조건, 참인 경우, 틀린 경우

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [59]:
type(np.where)

builtin_function_or_method

help 보는 방법
1. shift + tap : jupyter notebook에서 지원하는 기능 : docstring, signature를 보여줌
2. ?min or min? or ??min : jupyter notebook에서 지원하는 기능
3. help : python에서 기본적으로 제공하는 기능
4. np.info : numpy에 대한 상세한 도움말

In [62]:
help('min')
# 문자열도 인식함

Help on built-in function min in module builtins:

min(...)
    min(iterable, *[, default=obj, key=func]) -> value
    min(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its smallest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the smallest argument.



In [64]:
# for는 shift + tap 안됨...
# shift tap 해서 안나오면 help사용해서 찾아보기
help('for') # 정식 문서를 볼 때 사용

The "for" statement
*******************

The "for" statement is used to iterate over the elements of a sequence
(such as a string, tuple or list) or other iterable object:

   for_stmt ::= "for" target_list "in" expression_list ":" suite
                ["else" ":" suite]

The expression list is evaluated once; it should yield an iterable
object.  An iterator is created for the result of the
"expression_list".  The suite is then executed once for each item
provided by the iterator, in the order returned by the iterator.  Each
item in turn is assigned to the target list using the standard rules
for assignments (see Assignment statements), and then the suite is
executed.  When the items are exhausted (which is immediately when the
sequence is empty or an iterator raises a "StopIteration" exception),
the suite in the "else" clause, if present, is executed, and the loop
terminates.

A "break" statement executed in the first suite terminates the loop
without executing the "else" clause’s su

In [65]:
help('yield')

The "yield" statement
*********************

   yield_stmt ::= yield_expression

A "yield" statement is semantically equivalent to a yield expression.
The yield statement can be used to omit the parentheses that would
otherwise be required in the equivalent yield expression statement.
For example, the yield statements

   yield <expr>
   yield from <expr>

are equivalent to the yield expression statements

   (yield <expr>)
   (yield from <expr>)

Yield expressions and statements are only used when defining a
*generator* function, and are only used in the body of the generator
function.  Using yield in a function definition is sufficient to cause
that definition to create a generator function instead of a normal
function.

For full details of "yield" semantics, refer to the Yield expressions
section.

