# numpy  
빠르고
    1. 벡터화, 
    2. c로 만듦
사용하기 쉽다. (우아한 indexing)

In [1]:
import numpy as np

In [2]:
np.__version__
# 다른 library를 추가할 때는 version check 해야한다. 버전에 따라서 기능이 다를수도 있다.

'1.16.3'

Help 메뉴에서 numpy 공식 문서를 볼 수 있다.

numpy를 사용하기 위해서는 기존의 자료구조를 numpy type으로 바꿔줘야한다.

생성자를 이용하는 방식과 factory method를 이용하는 방식으로 인스턴스 생성(2가지)  
numpy는 팩토리 메소드 많이 사용함 = 객체를 반환하는 method

In [3]:
# python의 객체를 numpy객체로 바꿔주는 factory method
a = np.array([1,2,3])

In [5]:
np.__name__

'numpy'

In [6]:
type(a)
# 원래 이름은 numpy라서 np라고 출력안함

numpy.ndarray

In [7]:
a # 결과가 array()로 나오면 numpy format이다. import array랑 상관없다.

array([1, 2, 3])

In [ ]:
# import array == numpy array랑 다르다.

# 보통 pyhon의 array라고 하면, 2가지를 의미함
# 1. 일반적으로 array라고 하면 homogeneous data라고 함 : type이 같아서 data check안하니까 빠르게 처리가능(hetero보다 빠름)
# 2. n차원 벡터를 array라고 함
# numpy array는 두개 다 만족함
# python에도 array있음 
# 하지만 numpy가 더 빠름

# str byte bytearray range : homo한 contianer

In [12]:
%timeit sum(range(1000000))

20.3 ms ± 382 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit  np.sum(np.arange(1000000))
# 훯씬 빠름...!
# np.함수는 np.array에 최적화되어있어서 빠르다.

1.05 ms ± 8.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


stats model : R을 python도구
scikit-image, scikit learn, pandas, matplotlib 다 numpy기반

python느린데 해결책 

1. 좋은 컴퓨터 산다. --> 돈 많이 듦
2. 컴파일 하는 파이썬 사용 : cython --> 편하게 쓸 수 있는 라이브러리가 한정적이다.  
   pypy로 실행만 하면 속도가 훨씬 빨라진다. : 코드 안고쳐도 됨, library사용 가능  
   pypy가 python의 병목현상을 해결한다.
3. 내가 알고리즘을 잘 짠다.

# [벡터화](http://www.labri.fr/perso/nrougier/from-python-to-numpy/ )

벡터화를 통해서 numpy가 빠르다.  
벡터 형식으로 데이터를 한꺼번에 처리하는 기법 : 요즘 컴터는 벡터연산 최적화하는 코어가 있음 그래서 빠르다.  
벡터화, 행렬 : 묶어서 한꺼번에 계산함 == 효율적이다.

작은 데이터의 경우에는 오버헤드가 너무 크다.
데이터가 크면 성능이 좋을 수 밖에 없다.

In [18]:
a = np.array([1, 2, 3])

In [19]:
a # vector

array([1, 2, 3])

In [20]:
b = np.array([[1, 2, 3], [4, 5 ,6]])

In [21]:
b
# matlab은 행렬을 기본 자료형으로
# numpy나 R은 벡터를 기본 자료형으로
# 여기선 2차원 벡터를 행렬이라 하자

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
c = np.arange(10)
# range랑 유사한 함수, but vector로 만들어준다.
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
d = np.array([1, 2, '3'])
# 모두 homo하게 바꿈, 모두 str로 바꿈 == 왜???????????? 가장 큰거로 바꾼다는데;;;; 뭔뜻이지
# 더 큰 범위에 있는 type으로 변환된다.

In [33]:
d

array(['1', '2', '3'], dtype='<U21')

# 벡터 만드는 방법

In [28]:
np.sum(np.arange(10))
# python에서 제공하는 함수와 같은 함수가 많다. == 사용하기 쉽다.

45

In [30]:
e = np.zeros((2,5))
# 2행 5열

In [31]:
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
f = np.ones((2,5))

In [35]:
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
g = np.full((2,5), 10)

In [37]:
g

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [38]:
h = np.eye(5) # == np.identity(5)

In [39]:
h

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
i = np.identity(5)

In [41]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 벡터가 어떤 모양인지 확인하는 방법

In [42]:
i.dtype
# 각 원소의 type, homogeneous 라서 모든 원소의 타입이 같다.

# 윈도우가 32bit
# python이 32bit
# numpy가 32bit
# 중 하나라도 32ㅠㅑㅅaus 

dtype('float64')

In [43]:
i.shape
# (행, 열)

(5, 5)

In [44]:
i.size
# 원소의 수

25

In [45]:
i.ndim
# 차원의 수

2

# 차원마다 벡터를 부르는 용어
scalar : 0차원  
vector, 1D tensor : 1차원  
matrix, 2D tensor : 2차원  
ndarray, ND tensor : 3차원 이상...  

1차원 : 흑백 이미지  
3차원 : color image(r, g, b)  
4차원 : 애니메이션 (r, g, b, time)

# numpy array vs python list  
numpy array : homogeneous : 에다가 배열 형태. 다음 주솟값 찾기 쉽다, 데이터 type check할 필요 없다.  
sequence type : 연속으로 데이터 나열함(순서가 중요함) : indexing slicing가능  

python list : linked list라서 다음 주솟값 찾기 느리다.  
게다가 hetero여서 type check도 해줘야 한다.

In [48]:
a = [[1,2,3],[4,5,6]]

In [49]:
a

[[1, 2, 3], [4, 5, 6]]

In [50]:
a[1][0]

4

In [51]:
b = np.array(a)

In [52]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
b[1][0]
# 같은 방식으로 가져올 수 있다.
# 여러개 못 뽑는다

4

In [56]:
# 아래는 numpy만 가능한 기능들
b[1,0] # [] 하나로 처리함 : 편하다...

4

In [55]:
b[:,0]
# 모든 행에서 첫번째 원소만 가져온다.
# 1차원이라서 행벡터인지 열벡터인지 구분이 없다.

array([1, 4])

In [57]:
b[:,[1, 0]]
# 순서 바꿔서 가지고 옴 우와!!!
# 특정 데이터를 뽑아올 수 있다.

array([[2, 1],
       [5, 4]])

In [ ]:
b[[0,1]] # db레코드 참조할 때 요렇게 쓰지..?

b[1:4, 2:5]  
2행에서 4행을 모두 뽑아서  
3열에서 4열을 뽑음

In [58]:
b[:,[1,0]] = 9

In [59]:
b

array([[9, 9, 3],
       [9, 9, 6]])

# Fancy indexing

In [89]:
s = np.arange(10)

In [90]:
s[s > 5] # [] 한개만 씀
# 조건식으로 indexing할 수 있다.

array([6, 7, 8, 9])

In [92]:
s[[True, False, True, False, True,True, False, True, False, True]]
# masking 기법 : [[]] 2번 씀
# 특정 조건 써서 뽑는 기법

array([0, 2, 4, 5, 7, 9])

In [94]:
s[(s<5)&(s>3)]

array([4])

In [96]:
z = np.array([[1,2,3],[4,5,6]])

In [97]:
z[[1,0]]
# []안에 번호는 행 번호임 게다가 순서도 바꿀 수 있음
# db에서 record읽을 때 이런 방식으로 indexing하는 듯

array([[4, 5, 6],
       [1, 2, 3]])

numpy기반 함수와 자료구조를 쓰면 최적화가 되어 있음

# [stride](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.strides.html)라는 개념을 사용해서 구현
행렬처럼 1열로 만들었는데 고차원을 어떻게 표현한거지??  

Tuple of bytes to step in each dimension when traversing an array.

In [73]:
b.strides
# 모양을 바꾸는데 resource가 안 듦 : 계산만 하면 됨
# 숫자만 바꾸면 벡터 모양이 바뀜 == 속도가 빠름
# (24, 8) : 다음 행으로 이동하기 위해서 24byte이동해야하고 열을 이동하려면 8byte이동해야한다.

(24, 8)

In [62]:
b.dtype

dtype('int64')

In [64]:
a = np.arange(10).reshape(2,5)

In [65]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
a = np.arange(10).reshape(-1,5)
# -1 은 니가 알아서 계산하란 뜻
# 5 하나 주면, 나머지 값(2)은 알아서 계산해줌

In [67]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
a = np.arange(10).reshape(2, -1)
# -1 은 니가 알아서 계산하란 뜻
# 2 하나 주면, 나머지 값(5)은 알아서 계산해줌

In [70]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

python에서는 숫자형이 4가지(int, float, complex, bool) 밖에없는데,  
numpy는 type이 다양하다. 파이썬 고유 type + c type 지원

c처럼 data type을 지정할 수 있다. == c기반으로 만들었으니까  
typecode가 뭘까 == 단축표현

C(row-wise), 포트란(column wise) 데이터 읽는 방식을 2가지 다 지원한다.  
포트란에서 사용하는 데이터를 바로 가져올 수 있다.

network에서 문자 데이터 저장하는 방식을 지원해줌 : big endian, little endian

In [71]:
a = np.array([1, 2, 3], dtype='i1')

In [72]:
a

array([1, 2, 3], dtype=int8)

파이썬 장점 : 멀티 패러다임 : 다양한 관점으로 프로그래밍 가능하다. (vector방식도 지원)

In [74]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

In [77]:
def x(a, b):
    return [i+j for i,j in zip(a,b)]

In [78]:
x(a,b)

[7, 9, 11, 13, 15]

# Axis 어려우니 더 공부하자

In [83]:
c = np.array([a,b])

In [84]:
np.sum(c)
# axis안쓰면 모든 원소에 대해서 계산

55

In [85]:
np.sum(c, axis=0)
# 암기법 ㅣ (2,5)에서 첫 원소 가리면 (, 5) : 5개 나옴
# 열끼리 계산

array([ 7,  9, 11, 13, 15])

In [86]:
np.sum(c, axis=1)
# 암기법 ㅣ (2,5)에서 두 번째 원소 가리면 (2, ) : 2개 나옴
# 행끼리 계산
# panda는 numpy를 개선해서 axis='rows'사용 가능하게 해줌

array([15, 40])

# numpy는 matrix도 지원함
매트랩 쓰던사람을 위해서 만듦

np.array와 호환 가능하다. but array기반으로 하는것이 좋다.(R은 벡터기반)

In [87]:
mat = np.matrix([[1,2,3], [4,5,6]])

In [88]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

@ : numpy만을 위한 연산자

In [107]:
a = np.arange(55).reshape(5, -1)

In [108]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [110]:
a[0,2:5]
# 0행에서
# 2:5 까지

array([2, 3, 4])

In [109]:
a[:,2]
# 전체 행에서
# 2열만

array([ 2, 13, 24, 35, 46])

In [125]:
a[[2,4],0:6:2]

array([[22, 24, 26],
       [44, 46, 48]])

In [126]:
a[2:6:2,0:6:2]
# 시작: 끝 :stride

array([[22, 24, 26],
       [44, 46, 48]])

In [114]:
a[[2,4]][:,[0,2,4]]

array([[22, 24, 26],
       [44, 46, 48]])

In [ ]:
a[[-2,-1]][:,-2:]

In [119]:
a[[-2,-1]][:,-2:]

array([[42, 43],
       [53, 54]])

# numpy는 나만의 data타입 만들 수 있다.

In [160]:
a = [1, 2, 3]
b = a

In [161]:
b.append(4) 

In [162]:
print(a, b)
# 둘 다 바뀜 mutable이기 때문에
# 조심해야함...!

[1, 2, 3, 4] [1, 2, 3, 4]


In [167]:
a = [1, 2, 3]
b = a.copy()
# deep copy
# mutable일 때 값이 바뀌는 것이 싫으면 copy를 사용함

In [168]:
b.append(4)

In [171]:
b

[1, 2, 3, 4]

In [169]:
a
# a 가 안변함

[1, 2, 3]

In [17]:
x = np.array([1, 2, 3])

In [132]:
y = x

In [133]:
y + 3

array([4, 5, 6])

In [134]:
x

array([1, 2, 3])

In [135]:
y = y + 3 # 재할당됨, 메모리 번지가 바뀜

In [136]:
y

array([4, 5, 6])

In [137]:
x

array([1, 2, 3])

In [18]:
y = x

In [19]:
y = np.append(y, 4) # 중간값을 보여줌
# Note that `append` does not occur in-place: a new array is allocated and filled.

In [20]:
x

array([1, 2, 3])

In [21]:
y

array([1, 2, 3, 4])

In [189]:
x = np.arange(5)
y = x

In [190]:
y = np.append(y, 4) # 재할당 되서 같이 안변하는듯???????????
print(id(x),'\n',id(y))

4818059712 
 4818060272


In [191]:
x

array([0, 1, 2, 3, 4])

In [192]:
y

array([0, 1, 2, 3, 4, 4])

numpy는 기본적으로 mutable하다

In [16]:
# a를 바꿔도 b도 바뀐다. mutable하다
a = np.arange(10)
b = a # shallow copy 해서 문제가 생긴다.
# 할당할 때 copy를 써야 같이 안 변한다.

a[a>3] = 4
print(b)

[0 1 2 3 4 4 4 4 4 4]


In [185]:
a = np.arange(10)
b = np.copy(a) # 새로운 객체를 생성해줌
a[a>4] = 4
print(a,"\n",b)

[0 1 2 3 4 4 4 4 4 4] 
 [0 1 2 3 4 5 6 7 8 9]


# [View](https://studymake.tistory.com/406)

list는 slicing하면 새로운 객체가 생기지만, numpy의 경우에는 뷰가 생긴다.

In [15]:
arr = np.arange(10).reshape(2,5)
b = arr[0,:]
print(b)
arr[0,:] = 10
print(b)
# b 배열은 arr 배열의 첫 행에 대한 복사가 아니고 뷰(참조의 개념)이기 때문에 원본이 바뀌면 이 참조본도 따라서 바뀌게 된다.

[0 1 2 3 4]
[10 10 10 10 10]


In [13]:
arr = list([1,2,3,4,5,6,7,8])
b = arr[:4]
print(b)
arr[0] = 10
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [26]:
# column vector인데 왜 row vector로 표현하는 것일까?????????????
z = np.array([[1,2,3],[4,5,6]])
print(z[:,0], z[:,0].shape)
# 1차원으로 표현되어서 row처럼 표현됨
# https://stackoverflow.com/questions/17428621/python-differentiating-between-row-and-column-vectors

[1 4] (2,)
