(6,6) vs (6,6,1) ????  
(6,6) : 흑백  
(6,6,1) : 3차원 : color  

In [2]:
import numpy as np

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 제일 안 쪽 괄호가 행을 나타낸다. [1,2,3] : 행
# [[으로 시작하므로 2차원이다.
# 그다음 괄호가 열이다.

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a.dtype

dtype('int64')

In [14]:
a.shape
# 2행 3열 : 행렬

(3, 3)

<code>[[1],[2],[3]]</code> : 3행 1열   
맨 안 쪽 괄호가 행을 나타냄

# [np.newaxis](https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it)
제일 어렵다

https://docs.scipy.org/doc/numpy/user/quickstart.html

In [18]:
np.newaxis is None
# None ???

True

In [23]:
# 2차원에서 3차원으로 확장하는 문법, 그러나 None은 차원추가의 의미가 없어서 np.newaxis를 만듦
a[:,:,None] # 새로운 축을 추가하는 연산

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [24]:
a[:,:,np.newaxis] # 새로운 축을 추가하는 연산
# 원랜 None임

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [28]:
a[np.newaxis,:].shape
# 차원을 이동시켜서 분배한다.

(1, 3, 3)

In [29]:
a[:,np.newaxis].shape
# 축을 삽입

(3, 1, 3)

In [3]:
a = np.array([[[1,2],[3,4],[5,6]],[[9,9],[9,9],[9,9]]])

In [4]:
a
# 공백이 평면을 나눠줌

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[9, 9],
        [9, 9],
        [9, 9]]])

평면이 2장이 있다.  
[[1, 2],  
 [3, 4],  
 [5, 6]],  
아래
  
[[9, 9],  
 [9, 9],  
 [9, 9]]])  
위  

In [5]:
a = np.array([[1,2],[3,4],[5,6]])

In [6]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a[np.newaxis]
# 축이 하나 더 생긴것 뿐 값은 안 변한다.
# 근데 왜 a[:,:,np.newaxis]가 아닐까?????? 

# 흑백이미지를 칼라로 하려면 이 함수를 써야한다.

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
a[np.newaxis][0]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a[:,:,np.newaxis]

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [10]:
a[:,np.newaxis,:]

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [42]:
a[np.newaxis].shape
# 안에 평면이 하나
# x축을 만듦

(1, 3, 2)

In [44]:
a[np.newaxis]

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [46]:
a = np.array([1,2,3])

In [47]:
a.shape
# 방향이 있을 때 없을 때 shape가 다름

(3,)

In [48]:
a = np.array([[1,2,3]])

In [49]:
a.shape

(1, 3)

In [ ]:
x = np.array
# 평면이 어디에 있을까

x축 기준으로 만든 평면  
a[:,:,np.newaxis] : z축에 깊이감이 생김  
a[:,np.newaxis] : y축에 깊이감이 생김  
a[np.newaxis] : x축에 깊이감이 생김   
??????  

외부 라이브러리는 quick start가 항상 존재함   
따라서 공부할 때 quick start먼저 보면 됨

ndarray   
nd : n차원   
array : homo : type check안해서 빠르다.

In [54]:
a = np.array([[1,2],[3,4]])

In [55]:
a.shape

(2, 2)

In [56]:
a.ndim

2

In [57]:
a.size

4

# ndarray에서 제일 핵심적인 속성  
dtype, shape

이것들로 나머지 속성들을 추론할 수 있다.

In [61]:
a.itemsize
# byte

8

In [63]:
a.data
# 메모리 구조를 보여줌

reshape : stride값을 바꿔줌 == 속도 빠름, 메모리 실제 구조가 1행이라 빠르다  
but python 에서 list shape 바꾸려면, 모든 원소 일렬로 만들고 다시 구조를 만들어야 함 == 비효율

np.array()  
python 객체를 numpy객체로 바꿔주는 method

python에서는 duck type을 지원하기 때문에,   
list와 tuple은 차이점이 mutable밖에 없음  
np.array에서 사용하는 method가 똑같아서  
``` python
>>> b = np.array([(1.5,2,3), (4,5,6)])
>>> b
array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])
```
위의 두 연산은 같다.

In [65]:
from collections import namedtuple
# 원소를 sequence type 방식으로 & attribute로 접근 가능

In [66]:
x = namedtuple('Moon',['name','phone'])
# class만들 때 사용
# python은 객체지향이라 class를 만드는 방식이 다양함

In [68]:
a = x('아이린','010AAAABBBB')

In [69]:
type(a)
# Moon이 __main__ 현재 작업하고 있는 파일이 main에 있음

__main__.Moon

In [70]:
# 튜플이라 이렇게 사용가능
a[0]

'아이린'

In [71]:
a[1]

'010AAAABBBB'

In [72]:
# name으로 attribute access가능
a.name

'아이린'

# numpy도 자신만의 data type만들 수 있다.

In [73]:
np.linspace(1,100,100)
# 1에서 100 까지 100등분 시켜라
# 직선 구간을 균등하게 짤라서 각각 만듦

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

원랜 연산 하기전에 모양을 맞춰야 한다. element-wise하게 연산하니까  
사용자의 편의를 위해서 broadcasting기법으로 자동으로 맞춰준다.

# [Row-_and_column-major_order](https://en.wikipedia.org/wiki/Row-_and_column-major_order)
C : row wise하게 데이터 저장  
Fortran : column wise하게 데이터 저장

python에 존재하는 view 개념  
dict.items, dict.keys, dict.values  
indexing slicing : view

# python에서는 기본적으로 shallow copy이고
[Shallow and deep copy operations](https://docs.python.org/3/library/copy.html?highlight=copy#module-copy)  
[copy in Python](https://www.geeksforgeeks.org/copy-python-deep-copy-shallow-copy/)

# numpy는 기본적으로 deep copy이다.
[Numpy Views vs Copies: Avoiding Costly Mistakes](https://www.jessicayung.com/numpy-views-vs-copies-avoiding-costly-mistakes/)  
[Views versus copies in NumPy](https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html)  

In [6]:
a = [1,2,3,4]
b = a.copy()
print(id(a), id(b))
b[0] = 4 
print(a, b)
b.append(5)
print(a, b)
print(id(a),id(b))

2089407103112 2089407175112
[1, 2, 3, 4] [4, 2, 3, 4]
[1, 2, 3, 4] [4, 2, 3, 4, 5]
2089407103112 2089407175112


In [92]:
a = [[1,2],[3,4]] # 2차원일 땐 조심하자

b = a  (view)  
b = copy.deepcopy(a) (deep copy)  
b = a.copy() (shallow copy)

In [89]:
b = a.copy() # python은 기본적으로 shallow copy라서 문제가 많다.

In [90]:
b[0][0] = 4
# b[0][0] : 

In [85]:
b

[[4, 2], [3, 4]]

In [86]:
a

[[4, 2], [3, 4]]

In [87]:
import copy

In [88]:
a = [[1,2],[3,4]]

In [ ]:
b = copy.deepcopy(a)
# 깊은 곳 까지 copy하고 싶으면 deep copy해야 함

numpy는 기본적으로 deepcopy, python은 기본적으로 shallow copy  
python은 따로 호출 안해도 

# 1차원의 view와 copy구분하기 위해 명령어를 나눔

In [100]:
a = np.array([[1,2],[3,4]])

In [101]:
a.ravel() # view
# 라벨노래 유명한거 볼레로(view)

array([1, 2, 3, 4])

In [102]:
a.flatten() # copy

array([1, 2, 3, 4])

# np.newaxis, shallow deepcopy 따로 공부하기!!!!