# 1. Dynamic Programming

In [190]:
def fibA(num): 
    if num < 3:
        return 1
    a=b= 1
    for i in range(2, num):
            a, b = b, a+b
    return b

In [191]:
fibA(10)

55

In [193]:
%timeit fibA(100)

4.56 µs ± 30.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [76]:
strategy.append('Dynamic Programming')
performance.append(582e-9)

# 2. Recursion

tail recursion elimination
https://stackoverflow.com/questions/13543019/why-is-recursion-in-python-so-slow

In [194]:
def fibB(num): 
    if num < 3:
        return 1
    return fibB(num-1) + fibB(num-2)

In [195]:
fibB(10)

55

In [196]:
%timeit fibB(10)

9.98 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
strategy.append('Recursion')
performance.append(9.95e-6)

# 3. look-up table

In [197]:
def fibBB(num): 
    if num < 10:
        return [0,1,1,2,3,5,8,13,21,34,][num]#17 base cases
    return fibBB(num-1) + fibBB(num-2)

In [198]:
%timeit fibBB(10)

427 ns ± 8.81 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# 4. Dynamic (changing) look-up table (memoization) : Dynamic Programming

## 3.1

In [199]:
def fibC(num, dict):
    if num in dict:
          return dict[num]
    dict[num] = fibC(num-1, dict) + fibC(num-2, dict)
    return dict[num]

In [200]:
fibC(10,{1:1, 2:1})

55

In [201]:
%timeit fibC(10,{1:1, 2:1})

2.26 µs ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [79]:
strategy.append('Memoization')
performance.append(2.37e-6)

Making the dictionary global in fibC saves us from passing the dictionary. Nevertheless, using a global dictionary does NOT decrease the speed, and global variables are to be avoided where possible.

## 3.2

In [202]:
def fibD(num):
    if num in fibD.dict:
        return fibD.dict[num]
    fibD.dict[num] = fibD(num-1) + fibD(num-2)
    return fibD.dict[num]
fibD.dict = {1:1, 2:1}

In [203]:
fibD(10)

55

In [204]:
%timeit fibD(10)

155 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## 3.3

In [205]:
def fibE(num):
    def fib(num):
        if num in fib.dict:
            return fib.dict[num]
        fib.dict[num] = fib(num-1) + fib(num-2)
        return fib.dict[num]
    fib.dict = {1:1, 2:1}
    return (fib(num))

In [206]:
%timeit fibE(10)

4.06 µs ± 57.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 3.4

In [207]:
def fibF(num, dict = {1:1, 2:1}):
    if num in dict:
        return dict[num]
    dict[num] = fibF(num-1, dict) + fibF(num-2, dict)
    return dict[num]

In [208]:
fibF(10)

55

In [209]:
%timeit fibF(10)

110 ns ± 7.03 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## 3.5

In [210]:
def memoize(function):
    dict = {}                      
    def wrapper(num):           
        if num not in dict:
            dict[num] = function(num)
        return dict[num]
    return wrapper

@memoize    
def fibB(num):    
    if num < 3: return 1
    return fibB(num-1) + fibB(num-2)

In [211]:
%timeit fibB(10)

115 ns ± 5.61 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# Generator

In [116]:
def fib_generator(n):
    previous, current = 0, 1
    yield current
    i = 1
    while i < n:
        previous, current = current, previous + current
        yield current
        i += 1

In [157]:
x = fib_generator(10)
next(x)
next(x)
next(x)
next(x)
next(x)
next(x)
next(x)
next(x)
next(x)
next(x)

55

# Vectorize = no loop

## not-numpy

In [232]:
def fibG(num):
    from math import sqrt
    phi1 = (1 + sqrt(5))/2
    phi2 = (1 - sqrt(5))/2
    return round((phi1**num - phi2**num) / sqrt(5))

In [233]:
def fibGG(num):
    from math import sqrt
    sqrt5 = sqrt(5) 
    phi = (1 + sqrt5)/2
    return round((phi**num)/sqrt5) 

In [234]:
%timeit fibG(10)

4.83 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [235]:
%timeit fibGG(10)

4.72 µs ± 249 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## numpy

In [236]:
import numpy as np

In [237]:
def fibH(n):
    fib = np.zeros(n)
    fib[0], fib[1] = 1,1
    for i in range(2, n):
        fib[i] = fib[i-2] + fib[i-1]
    return fib[i]

In [238]:
fibH(10)

55.0

In [240]:
%timeit fibH(10)

3.34 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [241]:
def fibI(num):
    sqrt5 = np.sqrt(5)
    phi = (1+sqrt5)/2
    return np.round((phi**num)/sqrt5) 

In [244]:
fibI(10)

55.0

In [245]:
%timeit fibI(10)

3.22 µs ± 40.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [242]:
fibJ = np.vectorize(fibI)

In [243]:
%timeit fibJ(10)

18.8 µs ± 972 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [246]:
def fibL(num):
    sqrt5 = np.sqrt(5)
    phi = (1+sqrt5)/2
    a = (-phi*np.ones(num)).cumprod()
    return np.round((np.abs(a)-1/a)/sqrt5)

In [247]:
fibL(10)

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

In [248]:
%timeit fibL(10)

9.92 µs ± 59 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [147]:
fibI(10)

55.0

In [180]:
%timeit fibI(10)

3.14 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [160]:
def mm_fib(n):
    return (np.matrix([[2,1],[1,1]])**(n//2))[0,(n+1)%2]

In [161]:
mm_fib(10)

55

In [162]:
%timeit mm_fib(10)

15.3 µs ± 285 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [259]:
def fibJ(num):
    qmat = np.array([[1,1],[1,0]],dtype=object)
    return np.linalg.matrix_power(qmat,num)[0,1]

In [261]:
%timeit fibJ(10)

9.8 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [186]:
from numpy import matrix

def fibM(n):
    return (matrix('0 1; 1 1' if n >= 0 else '-1 1; 1 0', object) ** abs(n))[0, 1]

In [187]:
fibM(10)

55

In [188]:
%timeit fibM(10)

36.3 µs ± 1.61 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [1]:
from scipy import special

In [3]:
special.factorial([3,4])

array([ 6., 24.])

In [4]:
import inspect

In [6]:
print(inspect.getsource(special.factorial))

def factorial(n, exact=False):
    """
    The factorial of a number or array of numbers.

    The factorial of non-negative integer `n` is the product of all
    positive integers less than or equal to `n`::

        n! = n * (n - 1) * (n - 2) * ... * 1

    Parameters
    ----------
    n : int or array_like of ints
        Input values.  If ``n < 0``, the return value is 0.
    exact : bool, optional
        If True, calculate the answer exactly using long integer arithmetic.
        If False, result is approximated in floating point rapidly using the
        `gamma` function.
        Default is False.

    Returns
    -------
    nf : float or int or ndarray
        Factorial of `n`, as integer or float depending on `exact`.

    Notes
    -----
    For arrays with ``exact=True``, the factorial is computed only once, for
    the largest input, with each other result computed in the process.
    The output dtype is increased to ``int64`` or ``object`` if necessary.

    With ``exact

In [7]:
a = np.arange(10)

In [8]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(np.dot)

builtin_function_or_method

In [17]:
a = [3,4,5]

In [18]:
np.where(a>5,1,0)

TypeError: '>' not supported between instances of 'list' and 'int'

The "yield" statement
*********************

   yield_stmt ::= yield_expression

A "yield" statement is semantically equivalent to a yield expression.
The yield statement can be used to omit the parentheses that would
otherwise be required in the equivalent yield expression statement.
For example, the yield statements

   yield <expr>
   yield from <expr>

are equivalent to the yield expression statements

   (yield <expr>)
   (yield from <expr>)

Yield expressions and statements are only used when defining a
*generator* function, and are only used in the body of the generator
function.  Using yield in a function definition is sufficient to cause
that definition to create a generator function instead of a normal
function.

For full details of "yield" semantics, refer to the Yield expressions
section.



In [34]:
t