In [1]:
import numpy as np

In [2]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [3]:
a[3:,[0,2,5]]

array([[18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

In [4]:
a[[0,2,5],2]

array([ 2, 14, 32])

# [Integer array indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#integer-array-indexing)

In [5]:
a[[0,1,2,3,4],[1,2,3,4,5]]

array([ 1,  8, 15, 22, 29])

In [7]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
a[0]

array([0, 1, 2, 3, 4])

In [15]:
a[1,-2:]

array([8, 9])

In [13]:
a[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

In [14]:
a[-2::,-2::]

array([[18, 19],
       [23, 24]])

In [12]:
a[:,-1]

array([ 4,  9, 14, 19, 24])

In [23]:
a[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
a[0,1]

1

In [19]:
a[-2:,[0,1,3]]

array([[15, 16, 18],
       [20, 21, 23]])

In [21]:
a[[1,4],[1,1]]

array([ 6, 21])

In [22]:
a[[1,2,4],[2,3,4]]

array([ 7, 13, 24])